Repository GhagSagar23/vue_js_udemy, pull requests merged in 2025-09, with the labels that each got.

#14 Create update-and-deploy.yml
  .github/workflows/update-and-deploy.yml
Labels: ✨ enhancement, 🚀 deployment

#16 CSS Integration
  README.md
  index.html
  modules/02-css/exercises/css-integration-index.html
  progress-report.md
Labels: 📚 content, 📖 documentation, 📊 tracking

#19 Box Model
  README.md
  modules/02-css/exercises/topic-3/index.html
  modules/02-css/exercises/topic-3/style.css
Labels: 📚 content, 📖 documentation, 📊 tracking

#20 Typography showcase.
  README.md
  modules/02-css/exercises/topic-2/index.html
  modules/02-css/exercises/topic-2/style.css
Labels: 📚 content, 📖 documentation, 📊 tracking

#21 Pseudo Elements.
  README.md
  modules/02-css/exercises/topic-4/index.html
  modules/02-css/exercises/topic-4/style.css
Labels: 📚 content, 📖 documentation, 📊 tracking

#24 Website v2.0.
  index.html
  style.css
  style/background-effects.css
  style/experience-section.css
  style/layout-base.css
Labels: ✨ enhancement, ⚡ javascript, 🚀 deployment, 🔧 maintenance

#25 Task/website updates v2.1
  README.md
  index.html
  progress-report.md
  resources/profile.jpg
  style/profile-components.css
Labels: 📚 content, ✨ enhancement, 🎨 styling, ⚡ javascript, 🚀 deployment, 🔧 maintenance, 📊 tracking
